all: maple juice
maple: src/mapleWordCount.cpp
	g++ src/mapleWordCount.cpp -o mapleWordCount
juice: src/juiceWordCount.cpp
	g++ src/juiceWordCount.cpp -o juiceWordCount
clean:
	rm mapleWordCount juiceWordCount